Assumption = And(Array_Size(VG)==(9,3),Array_length(SignFlag)>=min(JoinTotal,5),ForAll(j, Implies(And(j>=0,j<min(JoinTotal,5)), VER_SignFlag[j]<9)))
G1 = And(Array_Size(Rtemp)==(3,5), Array_Size(VG_next)==(9,3), VG_next==VG)
G2 = Implies(gyroStatus0!=gyroStatus1,flgGyroCalc_next==235)
G3 = Implies(gyroStatus0!=gyroStatus1,And(Array_Size(TEMP_Rgtemp)==(5,3),ForAll([i,j], Implies(And(i>=0, i<min(JoinTotal,5),j>=0, j<3), VER_Rgtemp[i][j]==VER_VG[VER_SignFlag[i]][j])), ForAll([i,j], Implies(And(i>=min(JoinTotal,5),i<5,j>=0, j<3), VER_Rgtemp[i][j]==0))))
G4 = Implies(And(gyroStatus0!=gyroStatus1,min(JoinTotal,5)>=3, TEMP_rank==3),Rtemp_next==Rtemp)
G5 = Implies(And(gyroStatus0!=gyroStatus1,min(JoinTotal,5)<3, TEMP_rank==3),ForAll([i,j], Implies(And(i>=0,i<3,j>=0,j<5), VER_Rtemp_next[i][j]==0)))
G6 = Implies(gyroStatus0!=gyroStatus1,gyroStatus1_next==gyroStatus0)
G7 = Implies(gyroStatus0==gyroStatus1,And(flgGyroCalc_next==0,gyroStatus1_next==gyroStatus1))
G8 = Implies(gyroStatus0==gyroStatus1,ForAll([i,j], Implies(And(i>=0,i<3,j>=0,j<5), VER_Rtemp_next[i][j]==0)))
Guarantee = And(G1,G2,G3,G4,G5,G6,G7,G8)
contract = Implies(Assumption,Guarantee)
s.add(contract)
