Assumptions = And(Array_Size(VG)==(9,3),Array_length(SignFlag)>=min(JoinTotal,5),ForAll(j, Implies(And(j>=0,j<min(JoinTotal,5)), VER_SignFlag[j]<9)))
Guarantee1 = And(Array_Size(Rtemp)==(3,5), Array_Size(VG_next)==(9,3), VG_next==VG)
Guarantee2 = Implies(gyroStatus0!=gyroStatus1,And(gyroStatus1_next==gyroStatus0,flgGyroCalc_next==235, Array_Size(TEMP_Rgtemp)==(5,3),ForAll([i,j], Implies(And(i>=0, i<min(JoinTotal,5),j>=0, j<3), VER_Rgtemp[i][j]==VER_VG[VER_SignFlag[i]][j])), ForAll([i,j], Implies(And(i>=min(JoinTotal,5),i<5,j>=0, j<3), VER_Rgtemp[i][j]==0))))
Guarantee3 = Implies(And(gyroStatus0!=gyroStatus1,min(JoinTotal,5)>=3, TEMP_rank==3),Rtemp_next==Rtemp)
Guarantee4 = Implies(And(gyroStatus0!=gyroStatus1,min(JoinTotal,5)<3, TEMP_rank==3),ForAll([i,j], Implies(And(i>=0,i<3,j>=0,j<5), VER_Rtemp_next[i][j]==0)))
Guarantee5 = Implies(gyroStatus0==gyroStatus1,And(flgGyroCalc_next==0,gyroStatus1_next==gyroStatus1, ForAll([i,j], Implies(And(i>=0,i<3,j>=0,j<5), VER_Rtemp_next[i][j]==0))))
Guarantee0 = And(Guarantee1,Guarantee2,Guarantee3,Guarantee4,Guarantee5)
