###
Assumptions = Implies(rdLen==19, Array_length(pbuff)>=19)
Guarantee1 = (bComSuc==0)
Guarantee2 = (rdLen==19) 
Guarantee3 = (cntLenRdS_next==0)
Guarantee4 = And(cntLenRdS_next==cntLenRdS+1, totalLenRdS_next==totalLenRdS+1, cntLenRdO_next==cntLenRdO+1, totalLenRdO_next==totalLenRdO+1)
Guarantee5 = (pbuff[17]==frm)
Guarantee6 = And(cntUpdataO_next==0, cntUpdataS_next==0, frm_next==pbuff[17])
Guarantee7 = And(cntUpdataS_next==cntUpdataS+1, cntUpdataO_next==cntUpdataO+1, totalUpdataO_next==totalUpdataO+1, totalUpdataS_next==totalUpdataS+1)
Guarantee8 = And(pbuff[0]==235, pbuff[1]==144)
Guarantee9 = And(cntHeadO_next==0, cntHeadS_next==0)
Guarantee10 = And(cntHeadO_next==cntHeadO+1, cntHeadS_next==cntHeadS+1, totalHeadO_next==totalHeadO+1, totalHeadS_next==totalHeadS+1)
Guarantee11 = And(Array_Sum(pbuff,18)%255==pbuff[18])
Guarantee12 = And(cntCheckO_next==0, cntCheckS_next==0, bComSuc_next==3952088175)
Guarantee13 = And(cntCheckO_next==cntCheckO+1, cntCheckS_next==cntCheckS+1, totalCheckO_next==totalCheckO+1, totalCheckS_next==totalCheckS+1)
