A1 = And(Array_length(SignFlag)>=JoinTotal, JoinTotal<=5, Array_Size(Rtemp)==(3,5))
A2 = (ForAll(j, Implies(And(j>=0, j<JoinTotal), VER_SignFlag[j]<Array_length(wa))))
Assumptions = And(A1, A2)
Guarantee1 = And(Array_length(W_next)==3, Array_length(TEMP_tmpwa)==5)
G2_1 = ForAll(j, Implies(And(j>=0, j < JoinTotal),And(VER_TEMP_tmpwa_next[j]==VER_wa[ToInt(VER_SignFlag[j])])))
G2_2 = ForAll(j, Implies(And(j>=JoinTotal, j<5), VER_TEMP_tmpwa_next[j]==0))
Guarantee2 = And(G2_1, G2_2)
Guarantee3 = Implies(JoinTotal>=3, TEMP_W_next==W_next)
Guarantee4 = Implies(JoinTotal<3, And(VER_W_next[0]==0,VER_W_next[1]==0,VER_W_next[2]==0))
Guarantee0 = And(Guarantee1, Guarantee2, Guarantee3, Guarantee4)
