A1 = And(Array_length(SignFlag)>=JoinTotal, JoinTotal<=5, Array_Size(Rtemp)==(3,5))
A2 = (ForAll(j, Implies(And(j>=0, j<JoinTotal), VER_SignFlag[j]<Array_length(wa))))
Assumptions = And(A1, A2)
G1 = And(Array_length(W_next)==3, Array_length(TEMP_tmpwa)==5)
G2_1 = ForAll(j, Implies(And(j>=0, j < JoinTotal),And(VER_TEMP_tmpwa[j]==VER_wa[VER_SignFlag[j]])))
G2_2 = ForAll(j, Implies(And(j>=JoinTotal), VER_TEMP_tmpwa[j]==0))
G3 = Implies(JoinTotal>=3, TEMP_W==W_next)
G4 = Implies(JoinTotal<3, ForAll(i, Implies(And(i>=0, i<3), VER_W_next[i]==0)))
Guarantees = And(G1, G2_1, G2_2 ,G3, G4)
s.add(Implies(Assumptions, Guarantees))
s.add(Assumptions)
