Assumptions = True
DAMP1 = Implies(And(TripleFabsMax(pGyroRate[0], pGyroRate[1], pGyroRate[2])<0.15, Or(m_countPublic+1>time_D2P, countMode>time_D2P_overtime)), And(m_workMode_next==17, m_countMode_next==0,  m_countPublic_next==0))
DAMP2 = Implies(And(TripleFabsMax(pGyroRate[0], pGyroRate[1], pGyroRate[2])<0.15, m_countPublic+1<=time_D2P, countMode<=time_D2P_overtime), And(m_workMode_next==m_workMode, m_countMode_next==m_countMode, m_countPublic_next==m_countPublic+1))
DAMP3 = Implies(And(TripleFabsMax(pGyroRate[0], pGyroRate[1], pGyroRate[2])>=0.15, Or(m_countPublic>time_D2P, countMode>time_D2P_overtime)), And(m_workMode_next==17, m_countMode_next==0,  m_countPublic_next==0))
DAMP4 = Implies(And(TripleFabsMax(pGyroRate[0], pGyroRate[1], pGyroRate[2])>=0.15, m_countPublic<=time_D2P, countMode<=time_D2P_overtime), And(m_workMode_next==m_workMode, m_countMode_next==m_countMode, m_countPublic_next==m_countPublic))
DAMP = And(DAMP1, DAMP2, DAMP3, DAMP4)
Guarantee1 = And(m_workMode==0, DAMP)
PITCH1 = Implies(And(flgSP==235, abs(piyaw)>0.25, m_countPublic>11), And(workMode_temp==51, countMode_temp==0, countPublic_temp==0))
PITCH2 = Implies(And(flgSP==235, abs(piyaw)>0.25, m_countPublic<=11), And(workMode_temp==m_workMode, countMode_temp==m_countMode, countPublic_temp==m_countPublic+1))
PITCH3 = Implies(And(flgSP==235, abs(piyaw)<=0.25), And(workMode_temp==m_workMode, countMode_temp==m_countMode, countPublic_temp==m_countPublic))
PITCH4 = Implies(flgSP!=235, And(workMode_temp==m_workMode, countMode_temp==m_countMode, countPublic_temp==0))
PITCH5 = Implies(countMode_temp>4500, And(m_workMode_next==34, m_countPublic_next==0, m_countMode_next==0))
PITCH6 = Implies(countMode_temp<=4500, And(m_workMode_next==workMode_temp, m_countMode_next==countMode_temp, m_countPublic_next==countPublic_temp))
PITCH = Exists([workMode_temp, countMode_temp, countPublic_temp],And(PITCH1, PITCH2, PITCH3, PITCH4, PITCH5, PITCH6))
Guarantee2 = And(m_workMode==17, PITCH)
ROLL1 = Implies(And(flgSP==235, abs(royaw)>1, abs(m_countPublic)>11), And(workMode_temp==51, countMode_temp==0, countPublic_temp==0))
ROLL2 = Implies(And(flgSP==235, abs(royaw)>1, abs(m_countPublic)<=11), And(workMode_temp==m_workMode, countMode_temp==m_countMode, countPublic_temp==m_countPublic+1))
ROLL3 = Implies(And(flgSP==235, abs(royaw)<=1), And(workMode_temp==m_workMode, countMode_temp==m_countMode, countPublic_temp==m_countPublic))
ROLL4 = Implies(flgSP!=235, And(workMode_temp==m_workMode, countMode_temp==m_countMode, countPublic_temp==0))
ROLL5 = Implies(countMode_temp>5000, And(m_workMode_next==34, m_countPublic_next==0, m_countMode_next==0))
ROLL6 = Implies(countMode_temp<=5000, And(m_workMode_next==workMode_temp, m_countMode_next==countMode_temp, m_countPublic_next==countPublic_temp))
ROLL = Exists([workMode_temp, countMode_temp, countPublic_temp],And(ROLL1, ROLL2, ROLL3, ROLL4, ROLL5, ROLL6))
Guarantee3 = And(m_workMode==34, ROLL)
Guarantee4 = And(And(m_workMode!=0, m_workMode!=17, m_workMode!=34), And(m_workMode_next==m_workMode, m_countMode_next==m_countMode, m_countPublic_next==m_countPublic))
Guarantee0 = Exists(countMode, And(countMode==m_countMode+1, Or(Guarantee1, Guarantee2, Guarantee3, Guarantee4)))