s.add(i<9)
s.add(ForAll(i, Implies(And(i>=0, i<9), sum_temp(i)==sum_temp(i-1)+VER_tempFlag[i])))
s.add(sum_temp(-1)==0)
s.add(ForAll(i, Implies(And(i>=0, i<9), sum_gyro(i)==sum_gyro(i-1)+(VER_tempFlag[i]*(2**i)))))
s.add(sum_gyro(-1)==0)
Assumptions = (Array_length(StateFlag)>=9)
G1 = (Array_length(SignFlag_next)==9)
G2 = (Array_length(tempFlag)==9)
G3_1 = (ForAll(i, Implies(And(i>=0, i<9), Implies(VER_StateFlag[i]==235, VER_tempFlag[i]==1))))
G3_2 = (ForAll(i, Implies(And(i>=0, i<9), Implies(VER_StateFlag[i]!=235, VER_tempFlag[i]==0))))
G4 = (JoinTotal_next == Array_Sum(VER_tempFlag,8))
G5 = (ForAll(i, Implies(And(i>=0, i<JoinTotal_next), 
                        Exists(k, And(VER_SignFlag_next[i]==k, sum_temp(k)==i, Not(Exists(k1, And(k1<k, VER_SignFlag_next[i]==k1, sum_temp(k1)==i))))))))
G6 = (ForAll(i, Implies(And(i>=JoinTotal_next, i<9), VER_SignFlag_next[i]==0)))
G7 = (gyroStatus0_next == Array_Sum(VER_tempFlag,8))
Guarantees = And(G1, G2, G3_1, G3_2, G4, G5, G6, G7)
s.add(Implies(Assumptions, Guarantees))
print(s.check())
